# Generated by Django 2.1.7 on 2019-02-25 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearID', models.IntegerField()),
                ('stint', models.IntegerField()),
                ('teamID', models.IntegerField()),
                ('lgID', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('birthYear', models.IntegerField()),
                ('birthMonth', models.IntegerField()),
                ('birthDay', models.IntegerField()),
                ('birthCountry', models.CharField(max_length=255)),
                ('birthState', models.CharField(max_length=255)),
                ('birthCity', models.CharField(max_length=255)),
                ('deathYear', models.IntegerField(blank=True, null=True)),
                ('deathMonth', models.IntegerField(blank=True, null=True)),
                ('deathDay', models.IntegerField(blank=True, null=True)),
                ('deathCountry', models.CharField(blank=True, max_length=255, null=True)),
                ('deathState', models.CharField(blank=True, max_length=255, null=True)),
                ('deathCity', models.CharField(blank=True, max_length=255, null=True)),
                ('nameFirst', models.CharField(max_length=255)),
                ('nameLast', models.CharField(max_length=255)),
                ('nameGiven', models.CharField(max_length=255)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('bats', models.CharField(max_length=1)),
                ('throws', models.CharField(max_length=1)),
                ('debut', models.DateField()),
                ('finalGame', models.DateField(blank=True, null=True)),
                ('retroID', models.CharField(max_length=16)),
                ('bbrefID', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Pitching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearID', models.IntegerField()),
                ('stint', models.IntegerField()),
                ('teamID', models.IntegerField()),
                ('lgID', models.CharField(max_length=10)),
                ('W', models.IntegerField()),
                ('L', models.IntegerField()),
                ('G', models.IntegerField()),
                ('GS', models.IntegerField()),
                ('CG', models.IntegerField()),
                ('SHO', models.IntegerField()),
                ('SV', models.IntegerField()),
                ('IPOuts', models.IntegerField()),
                ('H', models.IntegerField()),
                ('ER', models.IntegerField()),
                ('HR', models.IntegerField()),
                ('BB', models.IntegerField()),
                ('SO', models.IntegerField()),
                ('BAOpp', models.FloatField()),
                ('ERA', models.FloatField()),
                ('IBB', models.IntegerField()),
                ('WP', models.IntegerField()),
                ('HBP', models.IntegerField()),
                ('BK', models.IntegerField()),
                ('BFP', models.IntegerField()),
                ('GF', models.IntegerField()),
                ('R', models.IntegerField()),
                ('SH', models.IntegerField()),
                ('SF', models.IntegerField()),
                ('GIDP', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bbapp.Master')),
            ],
        ),
        migrations.AddField(
            model_name='batting',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bbapp.Master'),
        ),
    ]
