# Generated by Django 2.1.7 on 2019-02-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitching',
            name='teamID',
            field=models.CharField(max_length=5),
        ),
    ]
