# Generated by Django 2.1.7 on 2019-03-03 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0002_auto_20190226_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fielding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearID', models.IntegerField(default=0)),
                ('stint', models.IntegerField(default=0)),
                ('teamID', models.CharField(max_length=5)),
                ('lgID', models.CharField(max_length=10)),
                ('Pos', models.CharField(max_length=5)),
                ('G', models.IntegerField(default=0)),
                ('GS', models.IntegerField(default=0)),
                ('InnOuts', models.IntegerField(default=0)),
                ('PO', models.IntegerField(default=0)),
                ('A', models.IntegerField(default=0)),
                ('E', models.IntegerField(default=0)),
                ('DP', models.IntegerField(default=0)),
                ('PB', models.IntegerField(blank=True, default=0, null=True)),
                ('WP', models.IntegerField(blank=True, default=0, null=True)),
                ('SB', models.IntegerField(blank=True, default=0, null=True)),
                ('CS', models.IntegerField(blank=True, default=0, null=True)),
                ('ZR', models.IntegerField(blank=True, default=0, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bbapp.Player')),
            ],
        ),
    ]
