# Generated by Django 2.1.7 on 2019-03-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0003_fielding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batting',
            name='teamID',
            field=models.CharField(max_length=5),
        ),
    ]
