# Generated by Django 2.1.7 on 2019-03-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0004_auto_20190303_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batting',
            name='BB',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batting',
            name='CS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batting',
            name='GIDP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batting',
            name='HBP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batting',
            name='IBB',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batting',
            name='SB',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batting',
            name='SF',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batting',
            name='SH',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielding',
            name='CS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielding',
            name='InnOuts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielding',
            name='PB',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielding',
            name='PO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielding',
            name='SB',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielding',
            name='WP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielding',
            name='ZR',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitching',
            name='BK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitching',
            name='ERA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitching',
            name='GF',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitching',
            name='GIDP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitching',
            name='IBB',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitching',
            name='SF',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitching',
            name='WP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='bats',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='bbrefID',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthDay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthMonth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthYear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='nameFirst',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='nameLast',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='retroID',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='throws',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
