# Generated by Django 2.1.7 on 2019-03-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0005_auto_20190305_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batting',
            name='AB',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batting',
            name='G',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batting',
            name='H',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batting',
            name='HR',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batting',
            name='R',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batting',
            name='RBI',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batting',
            name='SO',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batting',
            name='doubles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batting',
            name='triples',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielding',
            name='E',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fielding',
            name='GS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitching',
            name='BAOpp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitching',
            name='BFP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitching',
            name='HBP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitching',
            name='SH',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthCity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthCountry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='birthState',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='nameGiven',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
